[2025-10-29T01:10:44.062+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_training_pipeline.train_models manual__2025-10-29T01:08:07+00:00 [queued]>
[2025-10-29T01:10:44.159+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_training_pipeline.train_models manual__2025-10-29T01:08:07+00:00 [queued]>
[2025-10-29T01:10:44.160+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-29T01:10:44.170+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_models> on 2025-10-29 01:08:07+00:00
[2025-10-29T01:10:44.180+0000] {standard_task_runner.py:57} INFO - Started process 1949 to run task
[2025-10-29T01:10:44.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_training_pipeline', 'train_models', 'manual__2025-10-29T01:08:07+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/diabetes_training_pipeline.py', '--cfg-path', '/tmp/tmp_j87gum_']
[2025-10-29T01:10:44.191+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask train_models
[2025-10-29T01:10:44.269+0000] {task_command.py:416} INFO - Running <TaskInstance: diabetes_training_pipeline.train_models manual__2025-10-29T01:08:07+00:00 [running]> on host 8f23d0ceb5b8
[2025-10-29T01:10:44.344+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops_team' AIRFLOW_CTX_DAG_ID='diabetes_training_pipeline' AIRFLOW_CTX_TASK_ID='train_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T01:08:07+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-29T01:08:07+00:00'
[2025-10-29T01:10:46.678+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:10:46 INFO mlflow.tracking.fluent: Experiment with name 'diabetes_readmission_stage2' does not exist. Creating a new experiment.
[2025-10-29T01:10:47.326+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:10:47 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-29T01:10:54.376+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:10:54 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException("Unable to map 'object' type to MLflow DataType. object can be mapped iff all values have identical data type which is one of (string, (bytes or byterray),  int, float)."). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
[2025-10-29T01:10:58.026+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.10/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2025-10-29T01:10:58.251+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-29T01:10:59.121+0000] {logging_mixin.py:154} WARNING - Successfully registered model 'diabetes_readmit_logreg'.
[2025-10-29T01:10:59.306+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:10:59 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: diabetes_readmit_logreg, version 1
[2025-10-29T01:10:59.307+0000] {logging_mixin.py:154} WARNING - Created version '1' of model 'diabetes_readmit_logreg'.
[2025-10-29T01:11:10.370+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:11:10 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException("Unable to map 'object' type to MLflow DataType. object can be mapped iff all values have identical data type which is one of (string, (bytes or byterray),  int, float)."). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
[2025-10-29T01:11:12.115+0000] {logging_mixin.py:154} WARNING - Successfully registered model 'diabetes_readmit_gb'.
[2025-10-29T01:11:12.157+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:11:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: diabetes_readmit_gb, version 1
[2025-10-29T01:11:12.157+0000] {logging_mixin.py:154} WARNING - Created version '1' of model 'diabetes_readmit_gb'.
[2025-10-29T01:11:33.212+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/ensemble/_base.py:214 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T01:11:34.116+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/ensemble/_base.py:214 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T01:11:34.714+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/ensemble/_base.py:214 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T01:11:35.303+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/ensemble/_base.py:214 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T01:11:35.867+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:11:35 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException("Unable to map 'object' type to MLflow DataType. object can be mapped iff all values have identical data type which is one of (string, (bytes or byterray),  int, float)."). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
[2025-10-29T01:11:44.752+0000] {logging_mixin.py:154} WARNING - Successfully registered model 'diabetes_readmit_rf'.
[2025-10-29T01:11:44.811+0000] {logging_mixin.py:154} WARNING - 2025/10/29 01:11:44 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: diabetes_readmit_rf, version 1
[2025-10-29T01:11:44.811+0000] {logging_mixin.py:154} WARNING - Created version '1' of model 'diabetes_readmit_rf'.
[2025-10-29T01:11:45.022+0000] {python.py:194} INFO - Done. Returned value was: trained: ['logreg', 'gb', 'rf']
[2025-10-29T01:11:45.037+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=diabetes_training_pipeline, task_id=train_models, execution_date=20251029T010807, start_date=20251029T011044, end_date=20251029T011145
[2025-10-29T01:11:45.099+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-29T01:11:45.133+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
